### ISSUE TITLE
Scrolling and hitting Q at the same time in textual.app hung the script entirely

### ISSUE THREAD

**Issue by simonw** [willmcgugan/textual#13]
See attached video - if I hit Q while scrolling up and down with the trackpad I've occasionally managed to cause the terminal app to hang - such that it no longer responds to keyboard commands or scrolling, plus hitting Ctrl+C or even Ctrl+Z fails to exit it.

I recorded a video here with software that shows the keys I'm pressing:

https://user-images.githubusercontent.com/9599/122653493-bfe7b680-d0f9-11eb-9b71-c76fe32d10a8.mov

**Comment by simonw** [comment]
(This is very much a stress-test-induced bug, but I thought you may find it interesting)

**Comment by simonw** [comment]
Here's the `richtui.log` from one of my successful attempts to get this to happen. Note that the clock keeps on ticking, but everything else is unresponsive. https://gist.github.com/simonw/49f10e10ec0f2fc6261a48d8a4ff68d4

**Comment by willmcgugan** [comment]
Thanks for doing the investigation! It seems to occur when there are lots of queued messages, but frustratingly there are no exceptions logged.

One of the pain points of this is that I can't just let exceptions propagate, because it can leave the terminal in an unusable stage.

BTW what screen capture app do you use? I like the key press overlays.

**Comment by simonw** [comment]
I recorded it with QuickTime Player, but the screen overlays are https://github.com/keycastr/keycastr (just found it today)

**Comment by willmcgugan** [comment]
Fixed a deadlock in v0.1.2
